- name: Nginx and Php-FPM config
  hosts: web
  become: yes

  tasks:
  - name: Ensure packages is present
    apt: name={{item}} state=present update_cache=yes
    with_items:
      - nginx
      - php7.2
      - php7.2-fpm

  - name: Copy nginx config files
    copy:
      src: Nginx_conf/default
      dest: /etc/nginx/sites-available/default
      mode: '0777'
    notify:
      - Reload nginx

  - name: Copy start page
    synchronize:
      src: site/index.php
      dest: /var/www/html/index.php

  - name: Ensure services is running
    service:
      name: "{{item}}"
      state: started
    with_items:
      - nginx
      - php7.2-fpm

  handlers:
    - name: Reload nginx
      service:
        name: nginx
        state: reloaded